config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show, :destroy]

  namespace :admin do
    resources :users, only: [:index, :show, :destroy]
  end

  get "users/:id/update_status", to: "users#update_status",
    as: :update_status

  resources :foster_kids, except: [:new]

  resources :foster_parents, except: [:new]

  resources :foster_homes do
    resources :foster_kid_reviews, only: [:new, :create]
    resources :foster_parent_reviews, only: [:new, :create]
    resources :social_worker_reviews, only: [:new, :create]
    resources :social_worker_case_comments, only: [:new, :create]
  end

  resources :foster_homes do
    resources :foster_kids, only: [:edit, :update]
    resources :foster_parents, only: [:edit, :update]
  end

  get "foster_homes/:id/unassign", to: 'foster_homes#unassign',
    as: :foster_homes_unassign

  get "foster_homes/:id/thank_you", to: "foster_homes#thank_you",
    as: :foster_homes_thank_you

  get "home", to: "home#show"

  devise_scope :user do
    authenticated :user do
      root 'home#show', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user

  def show
    if current_user.admin?
      @foster_home = FosterHome.new
      @foster_kid = FosterKid.new
      @foster_parent = FosterParent.new
      @user_results = User.categories_for_user_dropdown
      @child_results = FosterKid.categories_for_child_dropdown
      @parent_results = FosterParent.categories_for_parent_dropdown
    else
      @user = current_user
      @user_active_foster_homes = @user.foster_homes.where(active: true).includes(:foster_kid).order("foster_kids.last_name")
      @user_inactive_foster_homes = @user.foster_homes.where(active: false).includes(:foster_kid).order("foster_kids.last_name")
    end
  end
end

app/views/home/_create_case.html.erb
<h3>Create Case Assignment</h3>
  <%= form_for @foster_home do |f| %>
    <div class="field">
      <%= f.label :foster_kid_id, "Select a Foster Child" %>
      <%= f.select(:foster_kid_id, options_for_select(@child_results), include_blank: true) %>
    </div>

    <div class="field">
      <%= f.label :foster_parent_id, "Select a Foster Parent" %>
      <%= f.select(:foster_parent_id, options_for_select(@parent_results), include_blank: true) %>
    </div>

    <div class="field">
      <%= f.label :user_id, "Assign To Social Worker:" %>
      <%= f.select(:user_id, options_for_select(@user_results), include_blank: true) %>
    </div>

    <div class="field">
      <%= f.label :active, "Active?" %>
      <%= f.check_box :active %>
    </div>

    <div class="actions">
      <%= f.submit "Assign Case", class: "button round submit" %>
    </div>
  <% end %>

app/views/home/_create_parent.html.erb
<h3>Add Foster Parent Information</h3>

<%= form_for @foster_parent do |f| %>
    <div class="field">
      <%= f.label :first_name, "First Name" %>
      <%= f.text_field :first_name %>
    </div>

    <div class="field">
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
    </div>

    <div class="actions">
      <%= f.submit "Add Foster Parent Information", class: "button round submit" %>
    </div>
<% end %>

app/views/home/_create_youth.html.erb
<h3>Add Foster Youth Information</h3>

<%= form_for @foster_kid do |f| %>
    <div class="field">
      <%= f.label :first_name, "First Name" %>
      <%= f.text_field :first_name %>
    </div>

    <div class="field">
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
    </div>

    <div class="actions">
      <%= f.submit "Add Foster Child Information", class: "button round submit" %>
    </div>
<% end %>

app/views/home/show.html.erb
<% if user_signed_in? %>
  <% if current_user.admin? %>

    <div class="row">
      <div class="small-6 small-centered columns">
        <h4>Admin Dashboard</h4>
      </div>
    </div>
    <div class="dashboard row">
      <div class="small-12 columns">
        <%= form_tag(admin_users_path, :method => "get") do %>
          <%= label_tag "Find Social Worker", params[:search] %>
          <%= select_tag :search, options_for_select(@user_results), include_blank: true %>
          <%= submit_tag "Search", :name => nil %>
        <% end %>
      </div>
    </div>
    <div class="dashboard actions row">
      <div class="small-12 columns">
        <%= link_to "See All Cases", foster_homes_path %>
        <br>
      </div>
    </div>

    <div class="dashboard row">
      <div class="small-12 small-centered columns">
        <ul class="tabs" data-tab>
          <li class="tab-title active"><a href="#panel1">Create Case</a></li>
          <li class="tab-title"><a href="#panel2">Add Foster Youth</a></li>
          <li class="tab-title"><a href="#panel3">Add Foster Parent</a></li>
          <li class="tab-title"><a href="#panel4">See All...</a></li>
        </ul>
        <div class="tabs-content">
          <div class="content active" id="panel1">
            <%= render "create_case" %>
          </div>
          <div class="content" id="panel2">
            <%= render "create_youth" %>
          </div>
          <div class="content" id="panel3">
            <%= render "create_parent" %>
          </div>
          <div class="content" id="panel4">
            <%= link_to "See All Foster Parents", foster_parents_path %>
            <br>
            <%= link_to "See All Foster Youth", foster_kids_path %>
            <br>
            <%= link_to "See All Social Workers", admin_users_path %>
            <br>
          </div>
        </div>
      </div>
    </div>

  <% else %>
    <h3>Welcome, <%= @user.first_name %> <%= @user.last_name %>!</h3>
      <% if !@user_active_foster_homes.empty? %>
        <h3>Your active cases:</h3>
        <% @user_active_foster_homes.each do |active_foster_home| %>
          <ul>
            <li><%= link_to active_foster_home.foster_kid.first_name + " " + active_foster_home.foster_kid.last_name, foster_home_path(active_foster_home) %></li>
          </ul>
        <% end %>
      <% else %>
        <h3><em>You do not currently have any active cases.</em></h3>
      <% end %>
      <% if !@user_inactive_foster_homes.empty? %>
      <h3>Your archived cases:</h3>
      <% @user_inactive_foster_homes.each do |inactive_foster_home| %>
        <ul>
          <li><%= link_to inactive_foster_home.foster_kid.first_name + " " + inactive_foster_home.foster_kid.last_name, foster_home_path(inactive_foster_home) %></li>
        </ul>
      <% end %>
    <% else %>
      <h3><em>You do not currently have any archived cases.</em></h3>
    <% end %>
  <% end %>
<% end %>

<script>
  $(document).foundation();
</script>