config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show, :destroy]

  namespace :admin do
    resources :users, only: [:index, :show, :destroy]
  end

  get "users/:id/update_status", to: "users#update_status",
    as: :update_status

  resources :foster_kids, except: [:new]

  resources :foster_parents, except: [:new]

  resources :foster_homes do
    resources :foster_kid_reviews, only: [:new, :create]
    resources :foster_parent_reviews, only: [:new, :create]
    resources :social_worker_reviews, only: [:new, :create]
    resources :social_worker_case_comments, only: [:new, :create]
  end

  resources :foster_homes do
    resources :foster_kids, only: [:edit, :update]
    resources :foster_parents, only: [:edit, :update]
  end

  get "foster_homes/:id/unassign", to: 'foster_homes#unassign',
    as: :foster_homes_unassign

  get "foster_homes/:id/thank_you", to: "foster_homes#thank_you",
    as: :foster_homes_thank_you

  get "home", to: "home#show"

  devise_scope :user do
    authenticated :user do
      root 'home#show', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

end

app/models/foster_home.rb
class FosterHome < ActiveRecord::Base
  belongs_to :foster_kid
  belongs_to :foster_parent
  belongs_to :user

  has_many :foster_kid_reviews
  has_many :foster_parent_reviews
  has_many :social_worker_reviews
  has_many :social_worker_case_comments 

  validates_inclusion_of :active, :in => [true, false]

end

app/controllers/foster_homes_controller.rb
class FosterHomesController < ApplicationController
  before_action :authenticate_user

  def index
    if current_user.admin?
      @active_foster_homes = FosterHome.where(active: true).includes(:foster_kid).order("foster_kids.last_name")
      @inactive_foster_homes = FosterHome.where(active: false).includes(:foster_kid).order("foster_kids.last_name")
    else
      raise_error
    end
  end

  def show
    @foster_home = FosterHome.find(params[:id])
    if current_user.admin? || @foster_home.user == current_user
      @foster_kid = @foster_home.foster_kid
      @foster_parent = @foster_home.foster_parent
      @foster_kid_reviews = @foster_home.foster_kid_reviews
      @foster_parent_reviews = @foster_home.foster_parent_reviews
      @social_worker_reviews = @foster_home.social_worker_reviews
      @social_worker_case_comments = @foster_home.social_worker_case_comments

      @all_home_reviews =
        @foster_kid_reviews + @foster_parent_reviews + @social_worker_reviews
      @all_home_reviews_by_date =
        @all_home_reviews.group_by_day { |review| review.created_at }
      @all_home_reviews_by_date.delete_if { |date, review| review.empty? }
      @series_a = @foster_kid_reviews.map { |r| [r.created_at.strftime("%m/%d/%Y"), r.rating] }.to_h
      @series_b = @foster_parent_reviews.map { |r| [r.created_at.strftime("%m/%d/%Y"), r.rating] }.to_h
      @series_c = @social_worker_reviews.map { |r| [r.created_at.strftime("%m/%d/%Y"), r.rating] }.to_h
    else
      raise_error
    end
  end

  def new
    if current_user.admin?
      @foster_home = FosterHome.new
      @user_results = User.categories_for_user_dropdown
      @child_results = FosterKid.categories_for_child_dropdown
      @parent_results = FosterParent.categories_for_parent_dropdown
    else
      raise_error
    end
  end

  def create
    if current_user.admin?
      @foster_home = FosterHome.new(foster_home_params)
      @foster_kid = FosterKid.find(params[:foster_home][:foster_kid_id])
      unless FosterHome.exists?(foster_kid_id: @foster_kid, active: true)
        if @foster_home.save
          redirect_to foster_home_path(@foster_home)
        else
          redirect_to new_foster_home_path
        end
      else
        flash[:notice] = "This foster youth has already been assigned to an active case."
        redirect_to authenticated_root_path
      end
    else
      raise_error
    end
  end

  def edit
    if current_user.admin?
      @foster_home = FosterHome.find(params[:id])
      @user_results = User.categories_for_user_dropdown
    else
      raise_error
    end
  end

  def update
    if current_user.admin?
      @foster_home = FosterHome.find(params[:id])
      if @foster_home.update_attributes(foster_home_params)
        flash[:notice] = "Foster home information successfully updated"
        redirect_to foster_home_path(@foster_home)
      else
        flash[:error] = "Please fill out all required fields."
        render :edit
      end
    else
      raise_error
    end
  end

  def unassign
    if current_user.admin?
      @foster_home = FosterHome.find(params[:id])
      @foster_home.user_id = nil
      if @foster_home.save!
        flash[:notice] = "This case has been successfully unassigned."
        redirect_to foster_home_path(@foster_home)
      else
        flash[:error] = "Error!"
        redirect_to foster_home_path(@foster_home)
      end
    else
      raise_error
    end
  end

  def thank_you
    @foster_home = FosterHome.find(params[:id])
    @foster_kid = @foster_home.foster_kid
    @foster_parent = @foster_home.foster_parent
    if current_user.admin? || current_user == @foster_home.user
      render :thank_you
    end
  end

  private

  def foster_home_params
    params.require(:foster_home).permit(
      :active,
      :foster_kid_id,
      :foster_parent_id,
      :user_id
    )
  end
end

app/views/foster_homes/_chart.html.erb
<%= line_chart [
{name: "Foster Youth", data: @series_a},
{name: "Foster Parent", data: @series_b},
{name: "Social Worker", data: @series_c},
],
   colors: ["blue", "red", "green"],
   library: {
     title: {
       text: "Case Quality Over Time"
     },
     tooltip: {
       xDateFormat: '%m-%d-%Y'
     },
     xAxis: {
       title: {
         text: "Date"
       },
       type: 'datetime',
       dateTimeLabelFormats: {
         day: '%e. %b'
       },
       tickPixelInterval: 5,
       tickWidth: 3,
       minTickInterval: 240 * 3600 * 1000,
       minRange: 30 * 24 * 3600 * 1000
     },
     yAxis: {
       allowDecimals: false,
       minorTickInterval: 1,
       title: {
         text: "Rating"
       },
       max: 10,
       min: 0
     }
     }%>

app/views/foster_homes/edit.html.erb
<h4>Update Case Assignment</h4>

<div class="row">
  <div class="small-12 small-centered columns form">
    <%= form_for @foster_home do |f| %>
      <div class="field">
        <%= f.label :user_id, "Assign To:" %>
        <%= f.select(:user_id, options_for_select(@user_results)) %>
      </div>

      <div class="field">
        <%= f.label :active, "Active?" %>
        <%= f.check_box :active %>
      </div>

      <div class="actions">
        <%= f.submit "Update Case", class: "button round submit" %>
      </div>
    <% end %>
  </div>
</div>

app/views/foster_homes/index.html.erb
<h3>Active Cases</h3>
<ul>
<% @active_foster_homes.each do |active_foster_home| %>
  <li><%= link_to "#{active_foster_home.foster_kid.last_name}", foster_home_path(active_foster_home) %></li>
<% end %>
</ul>

<h3>Archived Cases</h3>
<ul>
  <% @inactive_foster_homes.each do |inactive_foster_home| %>
    <li><%= link_to "#{inactive_foster_home.foster_kid.last_name}", foster_home_path(inactive_foster_home) %></li>
  <% end %>
</ul>

app/views/foster_homes/show.html.erb
<h3>Case Information</h3>

<% if @foster_home.active? %>
  <h3><em>Active</em></h3>
<% else %>
  <h3><em>Archived</em></h3>
<% end %>

<ul>
  <% unless @foster_home.user.nil? %>
    <li>Social Worker: <%= @foster_home.user.last_name %></li>
  <% else %>
    <li>Social Worker: Unassigned</li>
  <% end %>
    <li>Foster Youth: <%= @foster_home.foster_kid.last_name %></li>
    <% unless @foster_home.foster_parent.nil? %>
      <li>Foster Parent: <%= @foster_home.foster_parent.last_name %></li>
    <% else %>
      <li>Foster Parent: Unassigned</li>
    <% end %>
</ul>

<script src="https://code.highcharts.com/modules/no-data-to-display.js"></script>
<div id="container" style="width:90%; height:300px;" >
  <%= render "chart" %>
</div>

<div class="row">
  <div class="small-6 columns scrollbar">
    <h6 class="home-column"><strong>Reviews</strong></h6>
      <% if !@all_home_reviews_by_date.nil? %>
        <% @all_home_reviews_by_date.each do |date, reviews| %>
          <ul>
            <h6><%= date.strftime("%m/%d/%Y") %></h6>
            <% reviews.each do |review| %>
              <% if @foster_kid_reviews.include?(review) %>
              <h6>Foster Youth Review</h6>
              <% end %>
              <% if @foster_parent_reviews.include?(review) %>
              <h6>Foster Parent Review</h6>
              <% end %>
              <% if @social_worker_reviews.include?(review) %>
              <h6>Social Worker Review</h6>
              <% end %>
                <li>Rating: <%= review.rating %></li>
                <li>Comment: <%= review.comment %></li>
                <p>- - - - - - - - - - - - - -</p>
            <% end %>
            <br>
          </ul>
        <% end %>
      <% end %>
  </div>
  <div class="small-6 columns scrollbar">
    <h6 class="home-column"><strong>Quick Comments</strong></h6>
      <% if !@social_worker_case_comments.nil? %>
        <% @social_worker_case_comments.each do |comment| %>
          <ul>
            <li>
              <%= comment.created_at.strftime("%m/%d/%Y") %>: <%= comment.comment %>
            </li>
          </ul>
        <% end %>
      <% end %>
  </div>
</div>


<% if current_user.admin? %>
  <%= link_to "Reassign Case", edit_foster_home_path(@foster_home) %> |
  <%= link_to "Unassign Case", foster_homes_unassign_path(@foster_home), data: {confirm: "Are you sure you want to unassign this case?"} %> |
  <%= link_to "Quick Comment", new_foster_home_social_worker_case_comment_path(@foster_home) %> |
<% end %>

<%= link_to "Edit Foster Youth Information", edit_foster_home_foster_kid_path(@foster_home, @foster_kid) %> |

<% unless @foster_home.foster_parent.nil? %>
  <%= link_to "Edit Foster Parent Information", edit_foster_home_foster_parent_path(@foster_home, @foster_parent) %> |
<% end %>

<%= link_to "Add Foster Youth Review", new_foster_home_foster_kid_review_path(@foster_home, @foster_kid_review) %> |

<% unless @foster_home.foster_parent.nil? %>
  <%= link_to "Add Foster Parent Review", new_foster_home_foster_parent_review_path(@foster_home, @foster_parent_review) %> |
<% end %>

<%= link_to "Add Social Worker Review", new_foster_home_social_worker_review_path(@foster_home, @social_worker_review) %> |

app/views/foster_homes/thank_you.html.erb
<h4>Thank you for submitting your review! We take your feedback very seriously.</h4>

<div class="row">
  <div class="small-12 small-centered columns form">
    <%= form_tag do %>
      <%= label_tag :social_worker_access, "Are you the social worker on this case?" %>
      <%= select_tag :social_worker_access, options_for_select([["No", false],["Yes", true]]), include_blank: true %>
    <% end %>
  </div>
</div>

<div class="row">
  <div class="small-6 small-centered columns back-links">
    <h5 id="link_access"><%= link_to "Back", foster_home_path(@foster_home) %></h5>
  </div>
</div>