config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show, :destroy]

  namespace :admin do
    resources :users, only: [:index, :show, :destroy]
  end

  get "users/:id/update_status", to: "users#update_status",
    as: :update_status

  resources :foster_kids, except: [:new]

  resources :foster_parents, except: [:new]

  resources :foster_homes do
    resources :foster_kid_reviews, only: [:new, :create]
    resources :foster_parent_reviews, only: [:new, :create]
    resources :social_worker_reviews, only: [:new, :create]
    resources :social_worker_case_comments, only: [:new, :create]
  end

  resources :foster_homes do
    resources :foster_kids, only: [:edit, :update]
    resources :foster_parents, only: [:edit, :update]
  end

  get "foster_homes/:id/unassign", to: 'foster_homes#unassign',
    as: :foster_homes_unassign

  get "foster_homes/:id/thank_you", to: "foster_homes#thank_you",
    as: :foster_homes_thank_you

  get "home", to: "home#show"

  devise_scope :user do
    authenticated :user do
      root 'home#show', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

end

app/models/foster_kid.rb
class FosterKid < ActiveRecord::Base
  validates :first_name, presence: true
  validates :last_name, presence: true

  has_many :foster_homes
  has_many :users, through: :foster_homes
  has_many :foster_parents, through: :foster_homes

  def self.categories_for_child_dropdown
    all.map { |u| [u.last_name, u.id] }
  end

end

app/controllers/foster_kids_controller.rb
class FosterKidsController < ApplicationController
  before_action :authenticate_user

  def index
    if current_user.admin?
      @foster_kids = FosterKid.all.order("last_name ASC")
    else
      raise_error
    end
  end

  def show
    @foster_kid = FosterKid.find(params[:id])
    if current_user.admin? || FosterHome.exists?(foster_kid_id: @foster_kid, user_id: current_user)
      render :show
    else
      raise_error
    end
  end

  def create
    if current_user.admin?
      @foster_kid = FosterKid.new(foster_kid_params)
      unless FosterKid.exists?(first_name: @foster_kid.first_name, last_name: @foster_kid.last_name)
        if @foster_kid.save
          flash[:notice] = "Youth successfully added to site"
          redirect_to foster_kid_path(@foster_kid)
        else
          flash[:error] = @foster_kid.errors.full_messages.join('. ')
          redirect_to authenticated_root_path
        end
      else
        flash[:notice] = "This youth already exists in the database."
        redirect_to authenticated_root_path
      end
    else
      raise_error
    end
  end

  def edit
    @foster_kid = FosterKid.find(params[:id])
    if current_user.admin? || FosterHome.exists?(foster_kid_id: @foster_kid, user_id: current_user)
      render :edit
    else
      raise_error
    end
  end

  def update
    @foster_kid = FosterKid.find(params[:id])
    @foster_home = FosterHome.find_by(foster_kid_id: @foster_kid)
    if current_user.admin? || FosterHome.exists?(foster_kid_id: @foster_kid, user_id: current_user)
      if @foster_kid.update_attributes(foster_kid_params)
        flash[:notice] = "Child's information successfully updated"
        edit_origin = Rails.application.routes.recognize_path params[:route]
        if edit_origin.include?(:foster_home_id)
          redirect_to foster_home_path(@foster_home)
        else
          redirect_to foster_kid_path(@foster_kid)
        end
      else
        flash[:error] = "Please fill out all required fields."
        render :edit
      end
    else
      raise_error
    end
  end

  private

  def foster_kid_params
    params.require(:foster_kid).permit(
      :first_name,
      :last_name
    )
  end
end

app/views/foster_kids/edit.html.erb
<h4>Update Foster Child Information</h4>

<div class="row">
  <div class="small-12 small-centered columns form">
    <%= form_for @foster_kid do |f| %>
        <%= hidden_field_tag "route", request.env['PATH_INFO'] %>
        <div class="field">
          <%= f.label :first_name, "First Name" %>
          <%= f.text_field :first_name %>
        </div>

        <div class="field">
          <%= f.label :last_name %>
          <%= f.text_field :last_name %>
        </div>

        <div class="actions">
          <%= f.submit "Update", class: "button round submit" %>
        </div>
    <% end %>
  </div>
</div>

app/views/foster_kids/index.html.erb
<% if current_user.admin? %>
  <h3>All Foster Youth</h3>
<% else %>
  <h3>My Foster Youth</h3>
<% end %>

<ul>
<% @foster_kids.each do |foster_kid| %>
  <li><%= link_to foster_kid.first_name + " " + foster_kid.last_name, foster_kid_path(foster_kid) %></li>
<% end %>
</ul>

app/views/foster_kids/show.html.erb
<h3>Foster Youth Information</h3>

<ul>
  <li><%= @foster_kid.first_name %> <%= @foster_kid.last_name %></li>
</ul>

<%= link_to "Edit Child's Information", edit_foster_kid_path(@foster_kid) %>