config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show, :destroy]

  namespace :admin do
    resources :users, only: [:index, :show, :destroy]
  end

  get "users/:id/update_status", to: "users#update_status",
    as: :update_status

  resources :foster_kids, except: [:new]

  resources :foster_parents, except: [:new]

  resources :foster_homes do
    resources :foster_kid_reviews, only: [:new, :create]
    resources :foster_parent_reviews, only: [:new, :create]
    resources :social_worker_reviews, only: [:new, :create]
    resources :social_worker_case_comments, only: [:new, :create]
  end

  resources :foster_homes do
    resources :foster_kids, only: [:edit, :update]
    resources :foster_parents, only: [:edit, :update]
  end

  get "foster_homes/:id/unassign", to: 'foster_homes#unassign',
    as: :foster_homes_unassign

  get "foster_homes/:id/thank_you", to: "foster_homes#thank_you",
    as: :foster_homes_thank_you

  get "home", to: "home#show"

  devise_scope :user do
    authenticated :user do
      root 'home#show', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :foster_kids
  has_many :foster_homes

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates_inclusion_of :admin, :in => [true, false]

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_format_of :email, with: /\A[\w+\-.]+(@state.ma.us)\z/i, message: "(You need a state email address in order to register.)"

  validates_format_of :phone_number, with: /\(?([0-9]{3})\)?([ .-]?)([0-9]{3})\2([0-9]{4})/, message: "(Please enter your phone number in the following format: xxx-xxx-xxxx).", allow_blank: true

  def self.categories_for_user_dropdown
    all.map { |u| [u.last_name, u.id] }
  end

  def self.search(query)
    where("last_name LIKE ?", "%#{query}%")
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user

  def index
    if current_user.admin?
      if params[:search]
        @user = User.find(params[:search])
        @user_active_foster_homes = @user.foster_homes.where(active: true).includes(:foster_kid).order("foster_kids.last_name")
        @user_inactive_foster_homes = @user.foster_homes.where(active: false).includes(:foster_kid).order("foster_kids.last_name")
      else
        @users = User.all.order("last_name ASC")
      end
    else
      raise_error
    end
  end

  def destroy
    if current_user.admin?
      @user = User.find(params[:id])
      @user.destroy
      flash[:notice] = "#{@user.first_name} #{@user.last_name}'s account has been removed from the site."
      redirect_to admin_users_path
    else
      raise_error
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user

  def show
    @user = User.find(params[:id])
    if current_user == @user || current_user.admin?
      @user_active_foster_homes = @user.foster_homes.where(active: true).includes(:foster_kid).order("foster_kids.last_name")
      @user_inactive_foster_homes = @user.foster_homes.where(active: false).includes(:foster_kid).order("foster_kids.last_name")
    else
      raise_error
    end
  end

  def update_status
    @user = User.find(params[:id])
   #user's status will not be updated unless they have a state email address!
    if current_user.admin?
      if @user.admin?
        @user.update_attribute :admin, false
      else
        @user.update_attribute :admin, true
      end
      if @user.save
        if @user.admin == true
          flash[:notice] = "#{@user.first_name} #{@user.last_name} now has admin access."
          redirect_to admin_users_path
        else
          flash[:notice] = "#{@user.first_name} #{@user.last_name} has been removed from Admins."
          redirect_to admin_users_path
        end
      else
        raise_error
      end
    end
  end

end

app/views/admin/users/index.html.erb
  <% if params[:search] %>
    <% if @user_active_foster_homes.empty? && @user_inactive_foster_homes.empty? %>
      <h3><%= @user.last_name %> is available for new case assignments.</h3>
    <% else %>
      <% if !@user_active_foster_homes.empty? %>
        <h3><%= @user.last_name %>'s Active Cases</h3>
        <ul>
          <% @user_active_foster_homes.each do |active_foster_home| %>
            <li>
              <%= link_to "#{active_foster_home.foster_kid.last_name}", foster_home_path(active_foster_home) %>
            </li>
          <% end %>
        </ul>
      <% end %>

      <% if !@user_inactive_foster_homes.empty? %>
        <h3><%= @user.last_name %>'s Archived Cases</h3>
        <ul>
          <% @user_inactive_foster_homes.each do |inactive_foster_home| %>
            <li>
              <%= link_to "#{inactive_foster_home.foster_kid.last_name}", foster_home_path(inactive_foster_home) %>
            </li>
          <% end %>
        </ul>
      <% end %>
    <% end %>

  <% else %>
    <% @users.each do |user| %>
      <ul>
        <li><%= link_to "#{user.first_name} #{user.last_name}", user_path(user) %></li>
        <% if user.admin? %>
          <p><em>Admin</em></p>
        <% else %>
          <p><em>Non-Admin</em></p>
        <% end %>

        <% if current_user.admin? && user != current_user %>
          | <%= link_to "Remove User From Site", admin_user_path(user), method: :delete %> |
          <%= link_to "Update User's Privileges", update_status_path(user) %> |
        <% end %>

      </ul>
    <% end %>
  <% end %>